name: rota
base: core22
version: "2024.04.09"
summary: Gravity Bending Puzzle Platformer Game
description: |
  In ROTA gravity bends beneath your feet! Move blocks and twist 
  gravity to solve puzzles. Collect all 50 gems and explore 8 
  vibrant worlds

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

layout:
  /usr/lib/dotnet:
    bind: $SNAP/usr/lib/dotnet
  /usr/share/drirc.d:
    bind: $SNAP/usr/share/drirc.d
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/x86_64-linux-gnu/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
  /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
  /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so

parts:
  rota:
    plugin: dump
    source: snap/local
  libs:
    plugin: nil
    stage-packages:
      - libspeechd2
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
    prime:
      - usr/lib/*/libspeech*
      - usr/lib/*/dri
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/share/vulkan
      - usr/bin/vk*
  cleanup:
    after: [ rota ]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
apps:
  rota:
    command: bin/launch
    extensions: [gnome]
    plugs:
      - audio-playback
      - audio-record
      - network
      - network-bind
      - home
      - removable-media
      - joystick
      - wayland
      - opengl
      - hardware-observe
    environment:
      HOME: $SNAP_USER_COMMON
      VK_ICD_FILENAMESr: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json